remote_theme: just-the-docs/just-the-docs
plugins:
  #- jekyll-remote-theme
  - jekyll-seo-tag

title: SAS MoCa
description: >-
  A Bayesian-constrained analysis software for small-angle scattering (SAS) data of complex membrane systems.

baseurl: "/SAS_MoCa"
url: "https://pabstlab.github.io"

# Theme settings
search_enabled: true
heading_anchors: true

# Auxiliary links — appear in top-right corner
aux_links:
  "SAS_MoCa on GitHub": "https://github.com/PabstLab/SAS_MoCa"

# Footer content
footer_content: 'SAS MoCa &copy; Enrico F. Semeraro / Pabst Lab. Licensed under the BSD 3‑Clause “New” or “Revised” License.'

# Color scheme — options: nil (default/light), dark
color_scheme: dark

# Sort pages by nav_order first, then title
just_the_docs_collections:
  - name: pages
    nav_exclude: false
    search_exclude: false

# add logo
logo: "/docs/imgs/logo_sasmoca_dark.png"
# Optional: customize logo height
logo_width: 64
logo_height: 64
# Optional: link logo to homepage
logo_link: "/"
